# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install --production

# Copy app source
COPY . ./

# Expose default port
EXPOSE 3000

# Start the MCP HTTP server
CMD ["node", "server/index.js"]
